spring:
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      showSql: true
      formatSql: true
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
      jdbc.fetch_size: 200
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sbdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS SAMPLE_BANK
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO